[package]
name = "flutterbitch"
description = "Discord bot for BerryTube"
version = "0.3.0"
authors = ["Atte"]
license = "MIT"
publish = false
edition = "2018"
readme = "README.md"
repository = "https://github.com/Atte/discord-bot"

[dependencies]
base64 = "0.11"
chrono = "0.4"
digit_group = "0.1"
env_logger = "0.7"
error-chain = "0.12"
lazy_static = "1.4"
log = "0.4"
maplit = "1.0"
meval = "0.2"
percent-encoding = "2.1"
rand = "0.7"
regex = "1.3"
reqwest = "0.9"
serde = "1.0"
serde-aux = "0.6"
serde_derive = "1.0"
serde_json = "1.0"
serenity = "0.7"
toml = "0.5"
url = "2.1"
void = "1.0"

[dependencies.websocket]
version = "0.23"
default-features = false
features = ["sync", "sync-ssl"]
