[package]
name = "flutterbitch"
description = "Discord bot for BerryTube"
version = "0.1.0"
authors = ["Atte"]
license = "MIT"
publish = false

[dependencies]
env_logger = "0.5"
serenity = "0.5"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
error-chain = "0.11"
lazy_static = "1.0"
regex = "0.2"
maplit = "1.0"
log = "0.4"
meval = "0.1"
rand = "0.3"

[features]
default = []
reddit-debug = []
