[package]
name = "flutterbitch"
description = "Discord bot for BerryTube"
version = "0.1.0"
authors = ["Atte"]
license = "MIT"
publish = false

[workspace]

[dependencies]
env_logger = "0.5"
serenity = "0.5"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
error-chain = "0.12"
lazy_static = "1.0"
regex = "1.0"
maplit = "1.0"
log = "0.4"
meval = "0.1"
rand = "0.5"
chrono = "0.4"
url = "1.7"
digit_group = "0.1"
void = "1.0"

[features]
default = []
reddit-debug = []
