[package]
name = "flutterbitch"
description = "Discord bot for BerryTube"
version = "0.1.0"
authors = ["Atte"]
license = "MIT"
publish = false

[dependencies]
env_logger = "0.5"
serenity = "0.5"

[dependencies.log]
version = "0.4"
features = ["max_level_trace", "release_max_level_debug"]
