[package]
name = "discord-bot"
description = "Discord bot for BerryTube"
version = "0.1.0"
authors = ["Atte"]
license = "MIT"
publish = false
edition = "2018"
readme = "README.md"
repository = "https://github.com/Atte/discord-bot"

[dependencies]
env_logger = "0.7"
bytes = "0.5"
futures = "0.3"
lazy_static = "1.4"
log = "0.4"
itertools = "0.9"
meval = "0.2"
rand = "0.7"
regex = "1.3"
serde = "1.0"
serde_derive = "1.0"
serenity = "0.9.0-rc.0"
stable-eyre = "0.2"
tabwriter = "1.2"
toml = "0.5"
void = "1.0"

[dependencies.reqwest]
version = "0.10"
features = ["stream"]

[dependencies.tokio]
version = "0.2"
features = ["macros", "fs", "sync", "time", "io-util", "stream"]
