[package]
name = "discord-bot"
description = "Discord bot for BerryTube"
version = "0.1.0"
authors = ["Atte"]
license = "MIT"
publish = false
edition = "2018"
readme = "README.md"
repository = "https://github.com/Atte/discord-bot"

[dependencies]
env_logger = "0.8"
bytes = "1.0"
futures = "0.3"
itertools = "0.10"
lazy_static = "1.4"
log = "0.4"
meval = "0.2"
mongodb = "2.0.0-alpha"
rand = "0.8"
regex = "1.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde-aux = "2.1"
serenity = "0.10"
tabwriter = "1.2"
tokio-stream = "0.1"
toml = "0.5"
void = "1.0"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.reqwest]
version = "0.11"
features = ["stream"]

[dependencies.tokio]
version = "1.1"
features = ["fs", "macros", "rt", "sync", "time", "rt-multi-thread"]

[dependencies.eyre]
version = "0.6"
optional = true

[dependencies.stable-eyre]
version = "0.2"
optional = true

[features]
default = ["stable-eyre"]
nightly = ["eyre"]
