[package]
name = "discord-bot"
description = "Discord bot for BerryTube"
version = "0.1.1"
license = "MIT"
publish = false
edition = "2021"
readme = "README.md"
repository = "https://github.com/Atte/discord-bot"

[dependencies]
async-trait = "0.1"
base64 = "0.21"
bytes = "1.0"
color-eyre = "0.6"
conv = "0.3"
derivative = "2.2"
derive_more = "0.99"
env_logger = "0.10"
futures = "0.3"
itertools = "0.10"
lazy_static = "1.4"
linkify = { version = "0.10.0", optional = true }
log = "0.4"
maplit = "1.0"
meval = "0.2"
nonzero_ext = "0.3"
rand = "0.8"
regex = "1.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serenity = "0.11"
tabwriter = "1.2"
toml = "0.7"
void = "1.0"

[dependencies.zip]
version = "0.6"
default-features = false
features = ["deflate", "time"]

[dependencies.serde_with]
version = "2.0.0"
features = ["chrono"]

[dependencies.serde_repr]
version = "0.1"
optional = true

[dependencies.oauth2]
version = "4.1"
optional = true

[dependencies.rocket]
version = "=0.5.0-rc.3"
features = ["secrets", "json"]
optional = true

[dependencies.mongodb]
version = "2.0.2"
features = ["bson-chrono-0_4"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "gzip", "deflate"]

[dependencies.tokio]
version = "1.1"
features = ["fs", "macros", "rt", "sync", "time", "rt-multi-thread"]

[dependencies.tokio-stream]
version = "0.1"
optional = true

# needed by includedir, must be version 0.8.0
[dependencies.phf]
version = "0.8.0"
optional = true

[dependencies.includedir]
version = "0.6"
optional = true

[dependencies.governor]
version = "0.5"
optional = true

[dependencies.juniper]
version = "0.15"
optional = true

[dependencies.juniper_codegen]
version = "0.15"
optional = true

[dependencies.juniper_rocket]
version = "0.8"
optional = true

[dependencies.schemars]
version = "0.8"
optional = true

[dependencies.chrono-tz]
version = "0.8"
optional = true

[build-dependencies]
includedir_codegen = "0.6"

[dev-dependencies]
mock_instant = "0.3"
proptest = "1.1"

[features]
default = []
webui = ["rocket", "oauth2", "phf", "includedir", "governor", "juniper", "juniper_codegen", "juniper_rocket"]
webui-https = ["webui", "rocket/tls"]
berrytube = ["reqwest/stream", "tokio-stream"]
cron = []
teamup = ["serde_repr"]
openai = ["schemars"]
openai-functions = ["openai", "chrono-tz"]
openai-vision = ["openai", "linkify"]
