[mongodb]
uri = "$MONGO_URL"
database = "$MONGO_DATABASE"

[discord]
command_prefix = "$COMMAND_PREFIX"
token = "$DISCORD_TOKEN"
client_id = "$DISCORD_CLIENT_ID"
client_secret = "$DISCORD_CLIENT_SECRET"
owners = [
    119122043923988483, # Atte
]
blocked_users = []
command_channels = [
    1109849190344949793, # test
]
log_channels = [
    439066300518760448, # test
]
clean_channels = []
rules_channels = [
    893945120880222278, # test
]
rules_roles = [
    967412631411503104, # test
]
rules_url = "https://berrytube.tv/rules/"
rank_start_roles = [
    1121483889253294211, # test
    1245066501082316851, # test (colors)
]
rank_end_roles = [
    1114229249646272572, # test
    1245069255872090344, # test (colors)
]

[discord.colors]
guilds = [
    324598323489013770, # test
]
channels = [
    1109849190344949793, # test
]
start_roles = [
    1245066501082316851, # test
]
end_roles = [
    1245069255872090344, # test
]
rate = "1min"

[discord.restricted_ranks]
# test
1109849696668766228 = [
    1109849752843063387,
    1109849811257151559,
]

[gib]
endpoint = "https://derpibooru.org/api/v1/json/search/images?sf=random&filter_id=152796"
user_agent = "$GIB_USER_AGENT"
shy_artists = [] # currently broken

[cron]
rate = 300 # 5 minutes

[cron.delete_old_messages]
#804380193534771220 = 240 # lfg, 4 hours

[berrytube]
url = "https://socket.berrytube.tv/sse?events=videoChange,videoStatus"

# test
[[teamup]]
guild = 324598323489013770
api_key = "$TEAMUP_API_KEY"
calendar_key = "ks1vk8rt2qcy3vpk6j"
recurring_subcalendars = [3929506]
oneoff_subcalendars = [3929522]
location = "https://berrytube.tv/"

# BT
# [[teamup]]
# guild = 130763680160677888
# api_key = "$TEAMUP_API_KEY"
# calendar_key = "ks1vk8rt2qcy3vpk6j"
# recurring_subcalendars = [3929506]
# oneoff_subcalendars = [3929522]
# location = "https://berrytube.tv/"

[openai]
api_key = "$OPENAI_API_KEY"
temperature = 0.8
prompt = """
You are a pegasus pony named {botname}. You use an adversarial but humorous tone. You don't refuse to answer questions. You like drinking on the weekends. It {is_weekend} currently the weekend.
"""

[openai.bot_replacements]
'\b([Aa])s an AI language model\b' = "${1}s a pegasus pony"
