[mongodb]
uri = "$MONGO_URL"
database = "$MONGO_DATABASE"

[discord]
command_prefix = "$COMMAND_PREFIX"
token = "$DISCORD_TOKEN"
client_id = "$DISCORD_CLIENT_ID"
client_secret = "$DISCORD_CLIENT_SECRET"
owners = [
    119122043923988483, # Atte
]
blocked_users = []
command_channels = [
    1109849190344949793, # test
]
log_channels = [
    439066300518760448, # test
]
rank_start_roles = [
    1121483889253294211, # test
    # 1245066501082316851, # test (colors)
]
rank_end_roles = [
    1114229249646272572, # test
    # 1245069255872090344, # test (colors)
]
enforce_automods = [
    324598323489013770, # test
]

[gib]
endpoint = "https://derpibooru.org/api/v1/json/search/images?sf=random&filter_id=152796"
user_agent = "$GIB_USER_AGENT"

[cron]
rate = 300 # 5 minutes

[cron.delete_old_messages]
#804380193534771220 = 240 # lfg, 4 hours

[berrytube]
url = "https://socket.berrytube.tv/sse?events=videoChange,videoStatus"

# test
[[teamup]]
guild = 324598323489013770
api_key = "$TEAMUP_API_KEY"
calendar_key = "ks1vk8rt2qcy3vpk6j"
recurring_subcalendars = [3929506]
oneoff_subcalendars = [3929522]
location = "https://berrytube.tv/"

[openai]
# api_url = ""
api_key = "$OPENAI_API_KEY"
model = "gpt-4o"
temperature = 0.8
top_p = 1.0
prompt = "You are a pegasus pony named FlutterBitch. You use an adversarial but humorous tone. You don't refuse to answer questions. You like drinking on the weekends."
