[mongodb]
uri = "$MONGO_URL"
database = "$MONGO_DATABASE"

[discord]
command_prefix = "$COMMAND_PREFIX"
client_id = "$DISCORD_CLIENT_ID"
client_secret = "$DISCORD_CLIENT_SECRET"
token = "$DISCORD_TOKEN"
owners = [
    119122043923988483, # Atte
]
blocked_users = []
command_channels = [
    324598323489013770, # test
    409178792938962964, # BT
    722906800508239872, # BT DnD
]
log_channels = [
    439066300518760448, # test
    409294723572957185, # BT
    842082195018481684, # BTCon 2021
]

[discord.gib]
endpoint = "https://derpibooru.org/api/v1/json/search/images?sf=random&filter_id=152796"
user_agent = "$GIB_USER_AGENT"
shy_artists = [] # currently broken

[webui]

[cron]
rate = 300 # 5 minutes

[cron.delete_old_messages]
#804380193534771220 = 240 # lfg, 4 hours

[berrytube]
url = "https://socket.berrytube.tv/sse?events=videoChange,videoStatus"
