[mongodb]
uri = "$MONGO_URL"
database = "discord-bot"

[discord]
command_prefix = "$COMMAND_PREFIX"
token = "$DISCORD_TOKEN"
owners = [
    119122043923988483, # Atte
]
blocked_users = []
command_channels = [
    324598323489013770, # test
    409178792938962964, # BT
    722906800508239872, # BT DnD
]
log_channels = [
    439066300518760448, # test
    409294723572957185, # BT
]
sticky_roles = [
    543786595812376609, # sticky test
    276991279135457280, # Block NSFW
    369808034698100747, # Block politics
    409178686957420554, # Muted
]

[discord.gib]
endpoint = "https://derpibooru.org/api/v1/json/search/images?sf=random&filter_id=152796"
user_agent = "$GIB_USER_AGENT"
shy_artists = []

[berrytube]
enabled = true
url = "https://socket.berrytube.tv/sse?events=videoChange,videoStatus"
