cache_path = "cache.toml"

[discord]
command_prefix = "!"
deleted_msg_cache = 2048
username = "FlutterBitch"
token = "$DISCORD_TOKEN"
owners = [119122043923988483]
log_channels = [
    439066300518760448, # test
    409294723572957185 # BT
]

[reddit]
client_id = "8dPf_HbyOJaJJw"
client_secret = "$REDDIT_SECRET"
username = "FlutterBitchBot"
password = "$REDDIT_PASSWORD"
check_interval = 5 # minutes

[subreddits.BerryTubeLounge]
notify_channels = [350075683827089408]
