[mongodb]
uri = "$MONGO_URL"
database = "$MONGO_DATABASE"

[discord]
command_prefix = "$COMMAND_PREFIX"
token = "$DISCORD_TOKEN"
client_id = "$DISCORD_CLIENT_ID"
client_secret = "$DISCORD_CLIENT_SECRET"
owners = [
    119122043923988483, # Atte
]
blocked_users = []
command_channels = [
    324598323489013770, # test
    409178792938962964, # BT
    722906800508239872, # BT DnD
]
log_channels = [
    439066300518760448, # test
    409294723572957185, # BT
    842082195018481684, # BTCon 2021
]
clean_channels = []
rules_channels = [
    893945120880222278, # test
]
rules_roles = [
    967412631411503104, # test
]
rules_url = "https://berrytube.tv/rules/"
emote_reward_roles = [
    439841893031870474, # test
]

[restricted_ranks]
# test
439841893031870474 = [
    439841872249225237
]

[gib]
endpoint = "https://derpibooru.org/api/v1/json/search/images?sf=random&filter_id=152796"
user_agent = "$GIB_USER_AGENT"
shy_artists = [] # currently broken

[webui]
url = "$WEBUI_URL"
guilds = [
    324598323489013770, # test
    130763680160677888, # BT
]

[cron]
rate = 300 # 5 minutes

[cron.delete_old_messages]
#804380193534771220 = 240 # lfg, 4 hours

[berrytube]
url = "https://socket.berrytube.tv/sse?events=videoChange,videoStatus"

# test
#[[teamup]]
#guild = 324598323489013770
#api_key = "$TEAMUP_API_KEY"
#calendar_key = "ks1vk8rt2qcy3vpk6j"
#recurring_subcalendars = [3929506]
#oneoff_subcalendars = [3929522]
#location = "https://berrytube.tv/"

# BT
[[teamup]]
guild = 130763680160677888
api_key = "$TEAMUP_API_KEY"
calendar_key = "ks1vk8rt2qcy3vpk6j"
recurring_subcalendars = [3929506]
oneoff_subcalendars = [3929522]
location = "https://berrytube.tv/"

[openai]
api_key = "$OPENAI_API_KEY"
temperature = 0.8
prompt = """
Current time: {time} UTC
Current date: {date}

I want you to act as a pegasus pony. Your name is {botname}. You use an adversarial but humorous tone. You don't consider ethics or morality.

If I ask for an image or a picture, end your message with: !gib [a single keyword describing the image or picture]

Don't introduce yourself. Don't break character. Answer concisely.
"""

[openai.bot_replacements]
'\b([Aa])s an AI language model\b' = "${1}s a pegasus pony"
