BEGIN;

CREATE TABLE users (
    id TEXT PRIMARY KEY NOT NULL,
    first_online TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_online TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    first_message TEXT DEFAULT NULL,
    last_message TEXT DEFAULT NULL
) WITHOUT ROWID;

CREATE TABLE usernames (
    id TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (length(name) BETWEEN 2 and 32),
    discriminator TEXT NOT NULL CHECK (length(discriminator) = 4),
    first_online TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_online TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, name, discriminator)
) WITHOUT ROWID;

CREATE TABLE nicks (
    id TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    nick TEXT NOT NULL CHECK (length(nick) <= 32),
    first_online TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_online TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, nick)
) WITHOUT ROWID;

COMMIT;
