BEGIN;

CREATE TABLE reddit_seen (
    id TEXT PRIMARY KEY NOT NULL,
    time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
) WITHOUT ROWID;

CREATE TABLE gib_seen (
    id INTEGER PRIMARY KEY NOT NULL,
    time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
) WITHOUT ROWID;

CREATE TABLE sticky_roles (
    user_id TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id TEXT NOT NULL,
    time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
) WITHOUT ROWID;

COMMIT;
