BEGIN;

CREATE TABLE messages (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    json TEXT NOT NULL
) WITHOUT ROWID;

COMMIT;
