BEGIN;

CREATE TABLE channels (
    id TEXT NOT NULL PRIMARY KEY,
    guild_id TEXT NOT NULL,
    name TEXT NOT NULL,
    nsfw BOOLEAN NOT NULL DEFAULT FALSE,
    first_exists TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_exists TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
) WITHOUT ROWID;

COMMIT;
